spring.application.name=RIB

# DATABASE CONNECTION
spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=moise
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=true

#DEBUG
logging.level.org.springframework.web=DEBUG

#TEST-SEC
#spring.security.user.name=admin
#spring.security.user.password={noop}admin123

#MAIL
spring.mail.host=bsbdabvjdbhcavdvhasd
spring.mail.port=8080
spring.mail.password=wer45suw